### PR TITLE
Refactored: separated HTML from PHP into template files (FIX: #20)

### PR DESCRIPTION
**Pull request by micschk**
Refactored: separated HTML from PHP into template files (FIX: #20)

### CODE REVIEW

**Comment by camfindlay** [comment]
Does this work in parallel with #23? Ie. a dependancy between this PR and #23?

**Comment by micschk** [comment]
#23 includes some more edits in the template files which this PR introduces

**Comment by camfindlay** [comment]
Wanna put this all in to the same PR (#23) so it encapsulates the feature cleanly (lots of back and forth but we're almost there with this feature!  Exciting and very useful :D ).

**Comment by micschk** [comment]
OK, closing this PR as #23 includes all enhancements & updates so far.

**Pull request closed without merging**
