### PR TITLE
Upgrade/ss 4 upgrade

### PR DESCRIPTION
**Pull request by nickbyfleet**
Extend MemberAuthenticator and associated LoginHandler to provide a SS 4.x implementation of 2FA.

### CODE REVIEW

**Comment by nickbyfleet** [comment]
Whoops... wrong repo!

**Comment by camfindlay** [comment]
@nickbyfleet we'd be welcoming of a SS4 compatible version.... See #11 some other community members had started some work you might be able to draw from also!

**Comment by nickbyfleet** [comment]
Hi @camfindlay I've got a SS4 compatible version done at https://github.com/heyday/silverstripe-twofactorauth -- It's a bit of a WIP at the moment, but it works.

**Comment by camfindlay** [comment]
I'll need to branch off a `2` branch to maintain a SS3.x compatible version then you'd be welcome to go for gold on `master`~rather than maintain a forked copy of the module ;)

**Pull request closed without merging**
