### PR TITLE
UI refinements

### PR DESCRIPTION
**Pull request by oddnoc**
1. Remove the "lost password" link from the TOTP token form (the user has just used their password to get there)
2. Hide the security tokens behind a ToggleCompositeField and improve the formatting for backup tokens.

### CODE REVIEW

**Comment by camfindlay** [comment]
Let me know when you're close to a releasable master and we can review and tag a new major (2.0.0)

**Comment by oddnoc** [comment]
I think we're ready for 2.0.0, unless your team would like us to change something..

**Comment by camfindlay** [comment]
My "team" is me... this is under my personal GH account ;)

I'll look to give it an install and testing and then tag, for now you should be able to use dev-master though right?

**Comment by oddnoc** [comment]
Right, dev-master is fine for the moment, thanks!

**Pull request merged**
